language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
scripts:
- npm run build
deploy:
  provider: s3
  access_key_id: #TODO: Fill this in#
  secret_access_key: #TODO: Fill this in#
  bucket: #TODO: Fill this in#
  skip_cleanup: true
  local_dir: public
